### ISSUE TITLE
Fix file permissions while uploading

### ISSUE THREAD

**Issue by jaideep2** [BCCDC-PHL/illumina-uploader#13]
Currently in file permissions, Group write/delete access is enabled. Disable that so only NextSeq account can delete the data. if need be.

**Comment by dfornika** [comment]
This may not need any code changes, since the `chmod_command` is specified in the config file.

This chmod flag should give us the permissions we want:

`--chmod=Du=rwx,Dg=rx,Fu=rw,Fg=r,o=`

**Comment by jaideep2** [comment]
You are correct. As long as we are aware of what needs to change in config file. Closing!
