### ISSUE TITLE
Non-existent run directories may be added to the local SQLite db if they match the standard MiSeq run directory regex

### ISSUE THREAD

**Issue by dfornika** [BCCDC-PHL/illumina-uploader#2]
On [illumina-uploader-0.0.5](https://github.com/BCCDC-PHL/illumina-uploader/releases/tag/v0.0.5):

While testing a single-directory upload, I tried uploading a run directory that would be a valid run directory name, but doesn't actually exist in the MiSeqAnalysis directory of the local PC:

```
$ python illumina_uploader.py --config config.ini --upload_single_folder 201102_M00325_0256_000000000-G68FA
```

This run directory was still added to the local SQLite DB:

| folder | status | querylastrun |
|-- | -- | -- |
| 201102_M00325_0256_000000000-G68FG | CREATED | 04-Nov-2020 (10:27:43.754065) |
| 201102_M00325_0256_000000000-G68FA | CREATED | 04-Nov-2020 (10:55:54.685781) |

Run `201102_M00325_0256_000000000-G68FG` is a real, existing run but run `201102_M00325_0256_000000000-G68FA` is not.

**Comment by jaideep2** [comment]
Fixed in v0.0.6
