### ISSUE TITLE
'upload_complete.json' file not in valid .json format

### ISSUE THREAD

**Issue by dfornika** [BCCDC-PHL/illumina-uploader#26]
The `upload_complete.json` file that is copied to the remote server has the format:

```
timestamp_start:2021-03-10T15:45:06.624604-08:00 timestamp_end:2021-03-11T09:06:34.759959-08:00
```

It should be:
```json
{"timestamp_start": "2021-03-10T15:45:06.624604-08:00", "timestamp_end": "2021-03-11T09:06:34.759959-08:00"}
```

**Comment by jaideep2** [comment]
Disabling creating json file. Need to change process from rsync to scp, since its more intuitive. Also will work better with on-the-fly json creation.
