### ISSUE TITLE
Value of `timestamp_start` in `upload_complete.json` should correspond to start of upload

### ISSUE THREAD

**Issue by dfornika** [BCCDC-PHL/illumina-uploader#30]
The value of `timestamp_start` that is written in the `upload_complete.json` file does not match up with the timestamps we're seeing in `CompletedJobInfo.xml`.

The `timestamp_start` should be the time that the upload started.

**Comment by jaideep2** [comment]
Example for run 210329_M00325_0335_000000000-G7BBM
CompletedJobInfo.xml shows:
`<CompletionTime>2021-03-30T06:03:03.1591959-07:00</CompletionTime>`
whereas upload_complete.json shows:
`timestamp_start:2021-03-29T15:38:15.979793-07:00 timestamp_end:2021-03-30T07:49:24.340553-07:00 input_directory:/cygdrive/y/ output_directory:/data/miseq/MiSEQ_bakup_data/MMG/DATA_2021/`
